name: MMOAddon
version: '1.1'
main: kr.apo2073.mmoAddon.MMOAddons
api-version: '1.20'
authors: [ 아포칼립스 ]
depend: [ApoLib,  MythicLib, MMOItems]
softdepend:
  - PlaceHolder
  - Skript
  - MMOCore
  - MythicMobs
commands:
  getSkill:
  스킬북:
    description: 스킬북 생성 명령어
  스킬북추출:
    description: 스킬북 추출 명령어

permissions:
  mmoitems.*:
    children:
      mmoitems.skillbook: false
      mmoitems.magic: false
      mmoitems.skillbookO: false


  mmoitems.skillbook:
    default: op
  mmoitems.magic:
    default: op
  mmoitems.skillbookO:
    default: op